name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Generate SSH keys
      run: |
        ssh-keygen -t rsa -b 4096 -f configs/id_rsa -N ""
        mv configs/id_rsa.pub configs/authorized_keys
        chmod 600 configs/id_rsa configs/authorized_keys

    - name: Build Docker images
      run: |
        docker-compose build

    - name: Start containers
      run: |
        docker-compose up -d

    - name: Test SFTP connection
      run: |
        sleep 10  # Wait for containers to start
        sftp -i configs/id_rsa -P 2222 -o StrictHostKeyChecking=no sftpuser@localhost <<EOF
        put test.txt
        ls
        exit
        EOF
      env:
        test.txt: |
          echo "Test file" > test.txt

    - name: Test Nginx
      run: |
        curl --fail http://localhost

    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: phishing-simulation-framework-sftp
        severity: HIGH,CRITICAL
        format: table

    - name: Stop containers
      run: |
        docker-compose down